server:
  port: 8082
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: limit_route
          uri: http://localhost:8887/
          predicates:
            - Path=/**
          filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@userLevelRedisRateLimiter}"
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 300



logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.web: debug
